"""save additional polling information

Revision ID: aa1828e12501
Revises: 2a862cc7ef65
Create Date: 2023-12-08 11:59:53.655643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1828e12501'
down_revision: Union[str, None] = '2a862cc7ef65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_entry', sa.Column('health_check_response', sa.String(), nullable=False))
    op.add_column('poll_entry', sa.Column('readiness_check_response', sa.String(), nullable=False))
    op.add_column('poll_entry', sa.Column('metadata_response', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll_entry', 'metadata_response')
    op.drop_column('poll_entry', 'readiness_check_response')
    op.drop_column('poll_entry', 'health_check_response')
    # ### end Alembic commands ###
