"""optimisations

Revision ID: c82898e5c3d8
Revises: aa1828e12501
Create Date: 2023-12-08 13:07:59.332250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82898e5c3d8'
down_revision: Union[str, None] = 'aa1828e12501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_poll_entry_base_url'), 'poll_entry', ['base_url'], unique=False)
    op.create_index(op.f('ix_poll_entry_created_at'), 'poll_entry', ['created_at'], unique=False)
    op.create_index(op.f('ix_poll_entry_health_check_passed'), 'poll_entry', ['health_check_passed'], unique=False)
    op.create_index(op.f('ix_poll_entry_instance_version'), 'poll_entry', ['instance_version'], unique=False)
    op.create_index(op.f('ix_poll_entry_readiness_check_passed'), 'poll_entry', ['readiness_check_passed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_entry_readiness_check_passed'), table_name='poll_entry')
    op.drop_index(op.f('ix_poll_entry_instance_version'), table_name='poll_entry')
    op.drop_index(op.f('ix_poll_entry_health_check_passed'), table_name='poll_entry')
    op.drop_index(op.f('ix_poll_entry_created_at'), table_name='poll_entry')
    op.drop_index(op.f('ix_poll_entry_base_url'), table_name='poll_entry')
    # ### end Alembic commands ###
